### ISSUE TITLE
Technical Replicates Functionality

### ISSUE THREAD

**Issue by courtneyschiffman** [nhejazi/biotmle#20]
Include ability to specify technical replicates, similar to LIMMA

**Comment by nhejazi** [comment]
Currently, there appear to be two options for handling this:

1. A new argument (e.g., `samp_ids`) could be added to the main function `biomarkertmle`, to allow for repeated samples (i.e., technical replicates) to be handled within the `tmle::tmle` function. In the case of next-generation sequencing data (e.g., RNA-seq), this would occur after the `limma::voom` transform is applied to the raw data. The principal advantage of this approach is that it allows for repeated samples to be taken into account on the data after application of the influence curve transform.

2. An alternative would be to add facilities to allow the functions `limma::duplicateCorrelation` and `limma::voom` to be called in a repeated manner to obtain stabilized weights, as per [recommendations by the Smyth _et al_](https://support.bioconductor.org/p/59700/). This would likely be easiest to implement as a new internal function (perhaps called `repeatedSamples`), which could be called internally by the main function `biomarkertmle`, conditional on non-unique entries being present in the `samp_ids` argument described immediately above. The principal advantage to this would be a maintenance of consistency with current best practices in the use of the `limma` package, whilst disadvantages include reliance on (highly parametric) mixed effects models for repeated samples.

**Comment by nhejazi** [comment]
f907926 adds the new argument `subj_ids`, which handles technical replicates by passing a vector of unique identifiers directly to the `id` argument of `tmle::tmle(...)`.
