### ISSUE TITLE
`SummarizedExperiment` row names don't propagate to `modtest_ic()` output

### ISSUE THREAD

**Issue by PhilBoileau** [nhejazi/biotmle#78]
https://github.com/nhejazi/biotmle/blob/7d720af8393e561b54dd9f31d642ad943ce22d29/R/eif_moderated.R#L73-L88

The row names from the original `SummarizedExperiment` object fed to to `biomarkertmle()` don't appear as row names in the `topTable` slot of the `modtest_ic()` output. I think that this can be fixed by removing line 81 from above, and adding `ID = rownames(biotmle)` to the `mutate()` call.

**Comment by nhejazi** [comment]
Resovled by #79
